export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const AUTH_FAIL = 'AUTH_FAIL';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_FAIL = 'EMAIL_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOAD_PROFILE_USER = 'LOAD_PROFILE_USER';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_POSTS_TIMELINE = 'GET_POSTS_TIMELINE';
export const GET_POSTS_PROFILE = 'GET_POSTS_PROFILE';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const UPDATE_PICTURE = 'UPDATE_PICTURE';
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
